# Generated by Django 3.0.5 on 2020-04-24 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('my_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('UserId', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('Gender', models.CharField(blank=True, default='Male', max_length=50, null=True)),
                ('Years_in_US', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('Maritial_Status', models.PositiveSmallIntegerField(blank=True, default=1, null=True)),
                ('People_Family', models.PositiveSmallIntegerField(blank=True, default=4, null=True)),
                ('People_Household', models.PositiveSmallIntegerField(blank=True, default=4, null=True)),
                ('Family_income', models.FloatField(blank=True, default=4.978905533476001, null=True)),
                ('Household_Income', models.FloatField(blank=True, default=10.868016110700092, null=True)),
                ('GlycoHemoglobin', models.FloatField(blank=True, default=5.5642005502904315, null=True)),
                ('ArmCircum', models.FloatField(blank=True, default=28.52824824212779, null=True)),
                ('SaggitalAbdominal', models.FloatField(blank=True, default=21.00454499133802, null=True)),
                ('GripStrength', models.FloatField(blank=True, default=28.52824824212779, null=True)),
                ('Breast_fed', models.PositiveSmallIntegerField(blank=True, default=1.0, null=True)),
                ('Taking_Insulin', models.PositiveSmallIntegerField(blank=True, default=0.9600529909303984, null=True)),
                ('Taking_Oral_Agents', models.PositiveSmallIntegerField(blank=True, default=0.11780291450117192, null=True)),
                ('Eyes_Affected', models.PositiveSmallIntegerField(blank=True, default=0.07214918985019872, null=True)),
                ('Recent_BP', models.FloatField(blank=True, default=182.9334556200958, null=True)),
                ('Diabetes', models.PositiveSmallIntegerField(blank=True, default=0.18292061551003772, null=True)),
                ('medication', models.PositiveSmallIntegerField(blank=True, default=4, null=True)),
                ('age', models.PositiveSmallIntegerField(blank=True, default=4, null=True)),
                ('native_country', models.CharField(blank=True, default='United-States', max_length=150, null=True)),
                ('occupation', models.CharField(blank=True, default='Machine-op-inspct', max_length=100, null=True)),
                ('race', models.CharField(blank=True, default='Black', max_length=100, null=True)),
                ('workclass', models.CharField(blank=True, default='Private', max_length=100, null=True)),
                ('Total', models.FloatField(blank=True, default=117.55222663813309, null=True)),
            ],
        ),
    ]
